development:
  secret_token: <%= Settings.cookie_secret %>

test:
  secret_token: <%= Settings.cookie_secret %>
  secret_key_base: XX<%= Settings.cookie_secret %>
production:
   secret_token: <%= Settings.cookie_secret %>
   secret_key_base: <%= Settings.cookie_secret %>

